up:
	sudo docker-compose -f docker-compose.yaml up --build -d
down:
	sudo docker-compose -f docker-compose.yaml down

test run:
	sudo docker-compose -f docker-compose-test.yaml up -d

test down:
	sudo docker-compose -f docker-compose-test.yaml down
