# Generated by Django 4.2.1 on 2023-06-17 00:05

from django.db import (
    migrations,
    models
)


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_tguser_chat_id_alter_tguser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(null=True, verbose_name='Верификационный код'),
        ),
    ]
